### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by CaptainWolfz** [ipsk/CitizensCMD#1]
I Have a problem.
When  I want to add to Command to NPC with /npcmd add console say Welcome to server! ; Just there is a error > "An internal error occurred while attempting to perform this command''
Please help me :(

**Comment by ipsk** [comment]
Can you post the full error please?
Also I need a bit more information like, java version.

**Comment by CaptainWolfz** [comment]
Yes. Here is the Bug in Chat and in Console, my server is on version 1.12.2
Bug on Server/Chat: https://imgur.com/fnolXfS
Bug on Console: https://imgur.com/nZzAvii

**Comment by ipsk** [comment]
What is the java version your server is running on?

**Comment by CaptainWolfz** [comment]
How to find it? Im hosting my server on EGear.net

**Comment by ipsk** [comment]
I never used that hosting so I don't know, normally it's on the settings of your hosting page.

**Comment by ipsk** [comment]
What I am trying to say is that the problem most likely is because of the java version, it'll only work on java 8.

**Comment by CaptainWolfz** [comment]
Ok, i will contact Support of hosting.And than i will again contact you,Thanks ;)
